TrajectoryPlannerROS:

  holonomic_robot: false
  controller_frequency: 10.0000
  meter_scoring: True
  sim_time: 1.5
  pdist_scale: 0.3
  gdist_scale: 0.3

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.3

  max_vel_x: 0.6
  min_vel_x: 0.2
  acc_lim_x: 1.5
  acc_lim_theta: 1.5
  max_vel_theta: 0.5
